FROM alpine:3.20

ARG GIT_REVISION=unknown
ARG GIT_SOURCE=https://github.com/kuker24/SIAB1
ARG RELEASE_VERSION=unknown
ARG BUILD_CREATED=unknown
LABEL org.opencontainers.image.revision="${GIT_REVISION}" \
      org.opencontainers.image.source="${GIT_SOURCE}" \
      org.opencontainers.image.version="${RELEASE_VERSION}" \
      org.opencontainers.image.created="${BUILD_CREATED}"

RUN apk add --no-cache pgbouncer postgresql-client bash

COPY docker/pgbouncer/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh \
    && addgroup -S pgbouncer \
    && adduser -S -D -H -h /var/lib/pgbouncer -s /sbin/nologin -G pgbouncer pgbouncer \
    && mkdir -p /etc/pgbouncer \
    && chown -R pgbouncer:pgbouncer /etc/pgbouncer

USER pgbouncer

EXPOSE 6432

ENTRYPOINT ["/entrypoint.sh"]
